___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:200%; text-align:center; border-radius:10px 10px;">Data Analysis with Python</p>

![Image_Assignment](https://i.ibb.co/cY9HhF7/bnote-assignment.gif)

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#4d77cf; font-size:200%; text-align:center; border-radius:10px 10px;">Assignment 01 (NumPy & Pandas Basics)</p>

<a id="toc"></a>

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Content</p>

* [NUMPY SECTION](#0)
* [PANDAS SECTION](#1)


**In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!**

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Numpy Section</p>

<a id="0"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### 1. Import NumPy Library.

In [4]:
import numpy as np

### 2. Create an array from my_list = [5, 10, 15, 20, 25]

In [ ]:
my_list = [5, 10, 15, 20, 25]
my_list = np.array(my_list)
my_list

array([ 5, 10, 15, 20, 25])

In [ ]:
my_list = np.arange(5, 26, 5)
my_list

array([ 5, 10, 15, 20, 25])

### 3. Generate an array of 5x5 with zeros. 

In [ ]:
zeros = np.zeros([5,5])
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### 4. Generate an array of 4x4 with ones and assign data type as int.

In [ ]:
ones = np.ones([4,4], dtype = int)
ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

### 5. Make all the values of the array above with the value of 7.

In [ ]:
ones = np.full_like(ones, 7)
ones

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

### 6. Create the previous array above by full() method.

In [ ]:
sevens = np.full([4,4], 7)
sevens

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

### 7. Create an array of even integers from 2 to 16 (inclusive). 

In [ ]:
arr = np.arange(2,17,2, dtype = int)
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16])

### 8. Create a 5x5 matrix with the values between 0 to 25 (exclusive).

In [ ]:
arr_2 = np.reshape(np.arange(0,25), (5,5))
arr_2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### 9. Create a 5x5 matrix with the values between 0 to 25 (exclusive) using linspace method.

In [ ]:
arr_3 = np.reshape(np.linspace(0,24,25), (5,5))
arr_3

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

### 10. Create randomly 5 numbers with numpy.

In [ ]:
random_array = np.random.randint(5, size = 5,)
random_array

array([2, 0, 1, 2, 3])

### 11. Create an array of 5*5 shape and fills it with random values as per the standard normal distribution.

In [ ]:
random_array = np.random.randn(5,5)
random_array

array([[-0.43875712,  0.88889544,  1.41750835, -0.65737792,  1.71574163],
       [-1.11381307,  1.37229878, -0.59363383,  0.34604848,  0.98378521],
       [-0.82440253,  0.30957447,  0.58932577, -0.93370013, -0.25668932],
       [ 1.2554447 ,  0.2377892 ,  0.1963071 , -2.31974195, -0.73816707],
       [-0.5399826 ,  1.16290307,  0.58692905,  1.15166398, -0.28984019]])

In [ ]:
np.std(random_array)

0.9694516162028051

### 12. Create a 3*4 array of random int numbers between 20 and 50.

In [ ]:
random_int = np.random.randint(20,50, size = (3,4))
random_int

array([[20, 28, 30, 49],
       [38, 43, 29, 48],
       [28, 27, 29, 21]])

### 13. Create an array named "ranarr"consisting of randomly 48 numbers and reshape this array with the shape of 6x8 in different ways.

In [ ]:
ranarr = np.random.randint(0,100, size=48)
ranarr

array([89,  8, 92, 43, 85, 44, 20,  0, 89, 55, 85, 52, 11,  3,  4, 53, 36,
       92, 75, 79, 21, 84,  8, 93, 22, 44, 92, 37, 88, 56, 41, 48, 21,  1,
       18,  0, 57, 84,  6, 76, 37, 10, 84, 94, 92, 29, 43, 62])

In [ ]:
ranarr = np.reshape(ranarr, (6,8))
ranarr

array([[89,  8, 92, 43, 85, 44, 20,  0],
       [89, 55, 85, 52, 11,  3,  4, 53],
       [36, 92, 75, 79, 21, 84,  8, 93],
       [22, 44, 92, 37, 88, 56, 41, 48],
       [21,  1, 18,  0, 57, 84,  6, 76],
       [37, 10, 84, 94, 92, 29, 43, 62]])

In [ ]:
ranarr = np.reshape(ranarr, (-1,8))
ranarr

array([[89,  8, 92, 43, 85, 44, 20,  0],
       [89, 55, 85, 52, 11,  3,  4, 53],
       [36, 92, 75, 79, 21, 84,  8, 93],
       [22, 44, 92, 37, 88, 56, 41, 48],
       [21,  1, 18,  0, 57, 84,  6, 76],
       [37, 10, 84, 94, 92, 29, 43, 62]])

In [ ]:
ranarr = np.reshape(ranarr, (6,-1))
ranarr

array([[89,  8, 92, 43, 85, 44, 20,  0],
       [89, 55, 85, 52, 11,  3,  4, 53],
       [36, 92, 75, 79, 21, 84,  8, 93],
       [22, 44, 92, 37, 88, 56, 41, 48],
       [21,  1, 18,  0, 57, 84,  6, 76],
       [37, 10, 84, 94, 92, 29, 43, 62]])

## Numpy Indexing and Selection

### Create an array named "mat" in accordence with the desired output below.

In [ ]:
mat = np.arange(1,17).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### 14. Using the array above, write a code that reproduces the desired output shown below.<br>

In [ ]:
slice_mat = mat[1:3,1:3]
slice_mat

array([[ 6,  7],
       [10, 11]])

### 15. Get the 1st column (index number 0) of the array above.

In [ ]:
slice2_mat = mat[0:,0:1]
slice2_mat

array([[ 1],
       [ 5],
       [ 9],
       [13]])

### 16. Get the values in 2nd row (index number 1) for every 2 step.

In [ ]:
slice3_mat = mat [1:2,::2]
slice3_mat

array([[5, 7]])

### 17.Assign 77 to every cell in 3rd column.

In [ ]:
slice4_mat = mat[0:,2:3]=77
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

### 18. (a) Take 2nd row (index number 1) and 1st column (index number 0) , (b) 4th row (index number 3) and 3rd column (index number 2) .

In [ ]:
slice5_mat = mat[(1,3),(0,2)]
slice5_mat

array([ 5, 77])

### 19. Take between 2nd and last row with step 2 and between 1st and last column with step 2.

In [ ]:
slice6_mat = mat[1::2,0::2]
slice6_mat

array([[ 5, 77],
       [13, 77]])

## NumPy Operations

### 20. Get the sum of values smaller than 10 and values bigger than 12 in "mat".

In [ ]:
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [ ]:
# LET US FIND THE VALUES SMALLER THAN 10 IN "mat" 
mat[mat < 10]

array([1, 2, 4, 5, 6, 8, 9])

In [ ]:
# LET US FIND THE VALUES BIGGER THAN 12 IN "mat" 
mat[mat > 12]

array([77, 77, 77, 13, 14, 77, 16])

In [ ]:
# LET US SUM THE VALUES SMALLER THAN 10 AND BIGGER THAN 12 IN "mat" 
sum_mat = mat[mat < 10] + mat[mat > 12]
sum_mat

array([78, 79, 81, 18, 20, 85, 25])

### 21. Get the standard deviation (std) of the result above.

In [ ]:
# YOUR CODE IS HERE 
np.std(sum_mat)

29.700546274093877

### 22. Get the sum of the 2nd column in the original "mat".

In [ ]:
# LET US REMEMBER OUR ARRAY OF "mat" 
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [ ]:
# LET OBTAIN THE ORIGINAL ARRAY OF "mat" 
mat = np.arange(1,17).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
# YOUR CODE IS HERE 
np.sum(mat[::,1:2])

32

### 23. Get the median, mean and std of 3rd column in "mat".

In [ ]:
# LET US REMEMBER OUR ARRAY OF "mat" 
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
# LET US ASSIGN THE COLUMN WE ARE INTERESTED IN TO A VARIABLE 
third_column = mat[::,2:3]
third_column

array([[ 3],
       [ 7],
       [11],
       [15]])

In [ ]:
# WHAT IF WE ARE INTERESTED IN THE 3RD ROW? 
third_row = mat[2:3,::]
third_row

array([[ 9, 10, 11, 12]])

In [ ]:
# LET US GET MEDIAN VALUE 
print(f"{np.median(third_column)} & {np.median(third_row)}")

9.0 & 10.5


In [ ]:
# LET US GET MEAN VALUE 
print(f"{np.mean(third_column)} & {np.mean(third_row)}")

9.0 & 10.5


In [ ]:
# LET US GET STANDART DEVIATION (std) VALUE 
print(f"{np.std(third_column)}\n{np.std(third_row)}")

4.47213595499958
1.118033988749895


## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Pandas Section</p>

<a id="1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### Import Pandas Library

In [8]:
import pandas as pd

### Read Salaries.csv and take a look at the first 5 rows, df info and df statistical measurements.*

In [10]:
# LET US READ Salaries.csv 
df = pd.read_csv("/content/sample_data/Salaries.csv")

In [ ]:
# LET US LOOK AT THE FIRST 5 ROWS 
df.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

Desired Output:

![image.png](https://i.ibb.co/6BTmGX8/assignment1a.png)

In [ ]:
# LET US GET A SAMPLE 
df.sample()

Id   EmployeeName            JobTitle   BasePay  OvertimePay  \
23592  23593  INDIANA SAENZ  ELIGIBILITY WORKER  51098.32       737.79   

       OtherPay  Benefits  TotalPay  TotalPayBenefits  Year  Notes  \
23592    1445.0       NaN  53281.11          53281.11  2011    NaN   

              Agency  Status  
23592  San Francisco     NaN

Desired Output (WATCH OUT! Your output may NOT be the same as the one):

![image.png](https://i.ibb.co/mcsCxxC/assignment1b.png)

In [ ]:
# YOUR CODE IS HERE 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [ ]:
# LET US GET SOME DESCRIPTIVE MEASUREMENTS  
df.describe()

Id        BasePay    OvertimePay       OtherPay  \
count  148654.000000  148045.000000  148650.000000  148650.000000   
mean    74327.500000   66325.448840    5066.059886    3648.767297   
std     42912.857795   42764.635495   11454.380559    8056.601866   
min         1.000000    -166.010000      -0.010000   -7058.590000   
25%     37164.250000   33588.200000       0.000000       0.000000   
50%     74327.500000   65007.450000       0.000000     811.270000   
75%    111490.750000   94691.050000    4658.175000    4236.065000   
max    148654.000000  319275.010000  245131.880000  400184.250000   

            Benefits       TotalPay  TotalPayBenefits           Year  Notes  \
count  112491.000000  148654.000000     148654.000000  148654.000000    0.0   
mean    25007.893151   74768.321972      93692.554811    2012.522643    NaN   
std     15402.215858   50517.005274      62793.533483       1.117538    NaN   
min       -33.890000    -618.130000       -618.130000    2011.000000    NaN   
25%     11535.395000   36168.995000      44065.650000    2012.000000    NaN   
50%     28628.620000   71426.610000      92404.090000    2013.000000    NaN   
75%     35566.855000  105839.135000     132876.450000    2014.000000    NaN   
max     96570.660000  567595.430000     567595.430000    2014.000000    NaN   

       Status  
count     0.0  
mean      NaN  
std       NaN  
min       NaN  
25%       NaN  
50%       NaN  
75%       NaN  
max       NaN

Desired Output:

![image.png](https://i.ibb.co/ftMP67H/assignmnet1c.png)

### How many different year values are there?

In [ ]:
# YOUR CODE IS HERE 
df.value_counts("Year")

Year
2014    38123
2013    37606
2012    36766
2011    36159
dtype: int64

In [ ]:
# LET US FIND THE NUMBER OF UNIQUE VALUES IN THE COLUMN OF "Year"
df.Year.nunique()

4

In [ ]:
# LET US FIND THE UNIQUE VALUES IN THE COLUMN OF "Year"
df.Year.unique()

array([2011, 2012, 2013, 2014])

### Print out max and avg values in the column of "Totalpay".

In [17]:
# LET US FIND THE MAXIMUM TOTALPAY
df["TotalPay"].max()


567595.43

In [18]:
# LET US FIND THE AVERAGE TOTALPAY
df["TotalPay"].mean()

74768.32197169267

### How many records in the TotalPay column are there bigger than avg TotalPay?

In [42]:
# YOUR CODE IS HERE
df.loc[(df.TotalPay > df["TotalPay"].mean())]

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
135701  135702    Christina S Jee   
135778  135779  Mary Ann T Abille   
135847  135848   Emilda E Reinosa   
135853  135854      David G Evans   
136063  136064         Nicole Joe   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
135701                              Nurse Practitioner   70635.61   
135778                                   Special Nurse   60889.34   
135847                                   Special Nurse   76305.74   
135853                                   Special Nurse   71178.15   
136063                                   Special Nurse   61276.59   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011   
1         245131.88  137811.38       NaN  538909.28         538909.28  2011   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
135701         0.00    6550.41    771.88   77186.02          77957.90  2014   
135778      6815.67    9041.21    767.47   76746.22          77513.69  2014   
135847         0.00       0.00    763.08   76305.74          77068.82  2014   
135853      2748.15    2354.40    762.81   76280.70          77043.51  2014   
136063      8538.44    5078.67    748.95   74893.70          75642.65  2014   

        Notes         Agency  Status  
0         NaN  San Francisco     NaN  
1         NaN  San Francisco     NaN  
2         NaN  San Francisco     NaN  
3         NaN  San Francisco     NaN  
4         NaN  San Francisco     NaN  
...       ...            ...     ...  
135701    NaN  San Francisco     NaN  
135778    NaN  San Francisco     NaN  
135847    NaN  San Francisco     NaN  
135853    NaN  San Francisco     NaN  
136063    NaN  San Francisco     NaN  

[69489 rows x 13 columns]

Desired Output:

![image.png](https://i.ibb.co/nj84FbZ/assignment1d.png)

### How much does ALBERT PARDINI make money (including benefits)?

In [43]:
# YOUR CODE IS HERE 
df.loc[(df.EmployeeName == "ALBERT PARDINI"), ["TotalPayBenefits"]]

TotalPayBenefits
2         335279.91

### Who is the lowest paid person?

In [40]:
# YOUR CODE IS HERE 
df.groupby("TotalPay").max()

Id    EmployeeName  \
TotalPay                             
-618.13     148654       Joe Lopez   
 0.00       148653  Yao Zhang  Mai   
 0.30        36156    JOE BROWN JR   
 1.77        72925    Donald Clark   
 1.83       145930  Sylvia R Jones   
...            ...             ...   
 362844.66   36160  Gary Altenberg   
 390111.98  110533      Amy P Hart   
 471952.64  110532     David Shinn   
 538909.28       2    GARY JIMENEZ   
 567595.43       1  NATHANIEL FORD   

                                                  JobTitle    BasePay  \
TotalPay                                                                
-618.13                         Counselor, Log Cabin Ranch       0.00   
 0.00                       Wire Rope Cable Maint Mechanic       0.00   
 0.30                                     TRANSIT OPERATOR       0.00   
 1.77                                     Transit Operator       0.00   
 1.83                             Child Support Officer II       0.00   
...                                                    ...        ...   
 362844.66                    Lieutenant, Fire Suppression  128808.87   
 390111.98                               Asst Med Examiner  318835.49   
 471952.64                                  Deputy Chief 3  129150.01   
 538909.28                 CAPTAIN III (POLICE DEPARTMENT)  155966.02   
 567595.43  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   

            OvertimePay   OtherPay  Benefits  TotalPayBenefits  Year  Notes  \
TotalPay                                                                      
-618.13            0.00    -618.13      0.00           -618.13  2014    NaN   
 0.00              0.00       0.00   8308.87           8308.87  2014    NaN   
 0.30              0.00       0.30       NaN              0.30  2011    NaN   
 1.77              0.00       1.77      0.14              1.91  2012    NaN   
 1.83              0.00       1.83   4659.36           4661.19  2014    NaN   
...                 ...        ...       ...               ...   ...    ...   
 362844.66    220909.48   13126.31  44430.12         407274.78  2012    NaN   
 390111.98     10712.95   60563.54  89540.23         479652.21  2014    NaN   
 471952.64         0.00  342802.63  38780.04         510732.68  2014    NaN   
 538909.28    245131.88  137811.38       NaN         538909.28  2011    NaN   
 567595.43         0.00  400184.25       NaN         567595.43  2011    NaN   

                   Agency  Status  
TotalPay                           
-618.13     San Francisco     NaN  
 0.00       San Francisco     NaN  
 0.30       San Francisco     NaN  
 1.77       San Francisco     NaN  
 1.83       San Francisco     NaN  
...                   ...     ...  
 362844.66  San Francisco     NaN  
 390111.98  San Francisco     NaN  
 471952.64  San Francisco     NaN  
 538909.28  San Francisco     NaN  
 567595.43  San Francisco     NaN  

[138486 rows x 12 columns]

### What are the unique Jobs in dataset?

In [44]:
# YOUR CODE IS HERE 
df.JobTitle.unique()

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

### List the top 3 least common Jobs in the dataset.

In [45]:
# YOUR CODE IS HERE 
df["JobTitle"].value_counts().tail(3)

COURT COMPUTER FACILITIES COORDINATOR             1
AUTOMOTIVE BODY AND FENDER WORKER SUPERVISOR I    1
VICTIM & WITNESS TECHNICIAN                       1
Name: JobTitle, dtype: int64

### How many people earned more than avg in 2012?

### How many people have a title of Manager in their jobs?

### Take Id, EmployeeName, JobTitle, TotalPay and TotalPayBenefits columns with iloc and assign them as sal_new dataframe.

In [ ]:
# YOUR CODE IS HERE 



Desired Output:

![image.png](https://i.ibb.co/ZgFCbPm/assignment1e.png)

### Take the columns betweeen EmployeeName and TotalPayBenefits with loc and assign them as sal_new df.

In [ ]:
# YOUR CODE IS HERE 



Desired Output:

![image.png](https://i.ibb.co/s2CYS7H/assignment1f.png)

### Print out the names of the employees who earn more than min but less than avg.

In [ ]:
# YOUR CODE IS HERE 



Desired Output:

![image.png](https://i.ibb.co/mtNB2TX/assignment1g.png)

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

________